Upgrade OZ contracts with ERC721 approval workaround
ProjectOpenSea/opensea-creatures pull request #79
Opened 2021-04-15 01:29 UTC by TheMaxKim

Tested trading:

ERC721: https://testnets.opensea.io/assets/0x766f9cd1ca9bc7444862bc69ecf8b1bddc462004/9
ERC1155: https://testnets.opensea.io/assets/0x11a1aba7c6c3e458325577cb74d5a59f6a69639b/4

Upgrading OZ contracts caused trading to fail due to `_isApprovedForOwner` not calling the appropriate overridden `isApprovedForAll` method. Fixed but not yet in the latest OZ release: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2597

2021-04-19 16:33 UTC, sunwrobert approved these changes

2021-04-20 13:39 UTC, alexanderatallah commented on migrations/2_deploy_contracts.js
> -    await accessories.setApprovalForAll(
why is this no longer needed?

2021-04-20 13:39 UTC, alexanderatallah commented on test/ERC1155Tradable.js
> -           'OVERFLOW'
can we include a string that should be in the error message?

2021-04-20 13:41 UTC, alexanderatallah commented on contracts/ERC1155Tradable.sol
> +    require(balanceOf(msg.sender, _id) > 0, "ERC1155Tradable#ownersOnly: ONLY_OWNERS_ALLOWED");
should this be `_msgSender()`?

2021-04-20 13:41 UTC, alexanderatallah requested changes
added comments

2021-04-20 13:42 UTC, MINVEST01 commented
Hello you can include

  
>Вторник, 20 апреля 2021, 16:40 +03:00 от Alex Atallah ***@***.***>:
> 
> 
***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  test/ERC1155Tradable.js :
>> @@ -300,8 +301,7 @@ contract("ERC1155Tradable - ERC 1155", (accounts) => {
>              "0x0",
>              {from: creator}
>            ),
>-           truffleAssert.ErrorType.revert,
>-           'OVERFLOW'
>
>can we include a string that should be in the error message?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением к вашему делу
 

2021-04-20 22:59 UTC, flockonus commented on contracts/ERC721Tradable.sol
>      using Strings for string;
(my 2c as a bypasser) since you're using `abi.encodePacked` it seems safe to remove this line

2021-04-20 23:00 UTC, flockonus commented on contracts/ERC721Tradable.sol
>      using Strings for string;
Really appreciate this PR btw

2021-05-04 00:59 UTC, TheMaxKim commented on contracts/ERC721Tradable.sol
>      using Strings for string;
I believe you're right, removed it, nice catch!

2021-05-04 00:59 UTC, TheMaxKim commented on test/ERC1155Tradable.js
> -           'OVERFLOW'
The error message only returns "revert". It's not that helpful, but I've added a check for it.

2021-05-04 00:59 UTC, TheMaxKim commented on contracts/ERC1155Tradable.sol
> +    require(balanceOf(msg.sender, _id) > 0, "ERC1155Tradable#ownersOnly: ONLY_OWNERS_ALLOWED");
Yes, these should be, updated.

2021-05-04 01:03 UTC, TheMaxKim commented on migrations/2_deploy_contracts.js
> -    await accessories.setApprovalForAll(
So I believe this actually wasn't doing anything meaningful given the setApprovalForAll ABI: https://github.com/0xsequence/erc-1155/blob/master/src/contracts/tokens/ERC1155/ERC1155.sol#L160

This was causing an issue with the upgraded OZ contracts as they checked whether the operator was the same as the sender: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/token/ERC1155/ERC1155.sol#L106

2021-05-04 01:04 UTC, TheMaxKim commented
> added comments

Sorry for the delayed update on this, responded and updated.

2021-05-04 01:11 UTC, Striffly commented
Are these modifications still necessary since the 4.1 update of OpenZeppelin?

2021-05-04 01:44 UTC, TheMaxKim commented
> 
> 
> Are the ERC721 approval workaround changes still necessary since release of OpenZeppelin 4.1 ?

Ah, great, didn't catch that they had just released 4.1.0 which fixes the issue in question. Updating this.

2021-05-04 19:03 UTC, alexanderatallah approved these changes

2021-05-04 21:57 UTC, merged